Saurav = "TECH GODFATHER"
print(Saurav[0])
print(Saurav[1])
print(Saurav[2])
print(Saurav[3])
print(Saurav[4])
print(Saurav[5])
print(Saurav[6])
print(Saurav[7])
print(Saurav[8])
print(Saurav[9])
print(Saurav[10])
print(Saurav[11])
print(Saurav[12])
print(Saurav[13])
